### ISSUE TITLE
collect2.exe gives error

### ISSUE THREAD

**Issue by username7778** [ispras/swat#6]
hello
please help me with this obstacle thx
<a href="https://ibb.co/FBpRZcw"><img src="https://i.ibb.co/FBpRZcw/err2.png" alt="err2" border="0"></a>

**Comment by Dovgalyuk** [comment]
1. I see a python warning. Which version of python do you use?
2. Do you really need a Windows build? What function of SWAT do you want to use?

**Comment by username7778** [comment]
ty for replay
I use Python 3.9.6.
and I like to use this tool to observe patchguard.
I don't know if this can be done with the Linux build.
The function I need is only the WinDbg server.

**Comment by Dovgalyuk** [comment]
1. Can you build master branch of qemu in your environment? https://github.com/ispras/qemu
2. You can download the build with WinDbg support here: https://github.com/ispras/qemu/releases/tag/v2.7.50-windbg

**Comment by username7778** [comment]
1. unfortunately i got an error when compiling qemu
<a href="https://ibb.co/qjVBD2Q"><img src="https://i.ibb.co/qjVBD2Q/err3.png" alt="err3" border="0"></a>
2. ok that seems good to me
